server:
  port: 8502
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: bogeplus-massagist
  cloud:
    nacos:
      discovery:
        server-addr: localhost
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.3.230.36:3306/massage_massagist?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: rw_user
    password: Qq123123
  # redis
  redis:
    host: 119.3.230.36
    port: 6379
    password: Aa123123123 # 如果 Redis 没有设置密码，可以省略这一行
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    timeout: 3000ms

## 滑块验证码配置， 详细请看 cloud.tianai.captcha.autoconfiguration.ImageCaptchaProperties 类
#captcha:
#  expire:
#    default: 100000
#    # 文字点选验证码 过期时间设置大一点
#    WORD_IMAGE_CLICK: 60000
#  secondary:
#    enabled: false
#  # 初始化默认模板文件
#  init-default-resource: true
#  local-cache-enabled: true
#  local-cache-size: 20

# 配置openfeign 调用超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000

# mybatisPlus
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# mapper的debug日志
logging:
  level:
    com.bogeplus.pay.mapper: debug

##bybatis分页插件配置
#pagehelper:
#  # 设置方言，此处指定 MySQL 数据库
#  helper-dialect: mysql
#  # 是否启动合理化，默认是 false。
#  # 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages（最大页数）会查询最后一页。
#  # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
#  reasonable: true
#  # 是否支持接口参数来传递分页参数，默认false
#  support-methods-arguments: true
#  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值
#  params: count=countSql
#  # 默认值为 false，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）
#  page-size-zero: true
