server:
  port: 80
spring:
  application:
    name: bogeplus-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost
    gateway:
      routes:
        - id: bogeplus-user
          uri: lb://bogeplus-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: bogeplus-message
          uri: lb://bogeplus-message
          predicates:
            - Path=/message/**
          filters:
            - StripPrefix=1
        - id: bogeplus-activity
          uri: lb://bogeplus-activity
          predicates:
            - Path=/activity/**
          filters:
            - StripPrefix=1
        - id: bogeplus-order
          uri: lb://bogeplus-order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: bogeplus-pay
          uri: lb://bogeplus-pay
          predicates:
            - Path=/pay/**
          filters:
            - StripPrefix=1
        - id: bogeplus-massagist
          uri: lb://bogeplus-massagist
          predicates:
            - Path=/massagist/**
          filters:
            - StripPrefix=1


#      discovery:
#        server-addr:
#      config:
#        server-addr: