server:
  port: 80
spring:
  application:
    name: bogeplus-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost
    gateway:
      routes:
        - id: bogeplus-user
          uri: lb://bogeplus-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

#      discovery:
#        server-addr:
#      config:
#        server-addr: