server:
  port: 8101
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  application:
    name: bogeplus-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.3.230.36:3306/massage?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: rw_user
    password: 12345678

# redis
  redis:
    host: 119.3.230.36
    port: 6379
    password: Aa123123123 # 如果 Redis 没有设置密码，可以省略这一行
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    timeout: 3000ms


# mybatisPlus
# 稍后将mapper的 debug日志放在这里
# 滑块验证码配置， 详细请看 cloud.tianai.captcha.autoconfiguration.ImageCaptchaProperties 类
captcha:
  expire:
    default: 100000
    # 文字点选验证码 过期时间设置大一点
    WORD_IMAGE_CLICK: 60000
  secondary:
    enabled: false
  # 初始化默认模板文件
  init-default-resource: true
  local-cache-enabled: true
  local-cache-size: 20

